/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package resms.forms;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author Renz Joshua
 */
public class RealEstateApp extends javax.swing.JFrame {
    /**
     * Creates new form RealEstateApp
     */
    public RealEstateApp() {
        initComponents();
        setResizable(false);
        LogoIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resms/icons/logo.png")));
        
        Border tb = BorderFactory.createMatteBorder(0,0,3,0, Color.white);
        BuyLot.setBorder(tb);
        BuyLotIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resms/icons/properties.png")));
        
        AddLot.setBorder(tb);
        AddLotIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resms/icons/report.png")));
        
        ViewSales.setBorder(tb);
        ViewSalesIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resms/icons/sales.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LogoIcon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BuyLotIcon = new javax.swing.JLabel();
        AddLotIcon = new javax.swing.JLabel();
        AddLot = new javax.swing.JLabel();
        ViewSalesIcon = new javax.swing.JLabel();
        ViewSales = new javax.swing.JLabel();
        BuyLot = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(249, 226, 175));

        jPanel7.setBackground(new java.awt.Color(0, 159, 189));

        jPanel4.setBackground(new java.awt.Color(74, 36, 157));
        jPanel4.setForeground(new java.awt.Color(74, 36, 157));

        jPanel3.setBackground(new java.awt.Color(0, 159, 189));

        BuyLotIcon.setText("jLabel1");

        AddLotIcon.setText("jLabel1");

        AddLot.setBackground(new java.awt.Color(0, 159, 189));
        AddLot.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        AddLot.setForeground(new java.awt.Color(255, 255, 255));
        AddLot.setText("  Add Lot");
        AddLot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddLot.setOpaque(true);
        AddLot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddLotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddLotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddLotMouseExited(evt);
            }
        });

        ViewSalesIcon.setText("jLabel1");

        ViewSales.setBackground(new java.awt.Color(0, 159, 189));
        ViewSales.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ViewSales.setForeground(new java.awt.Color(255, 255, 255));
        ViewSales.setText("  View Sales");
        ViewSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ViewSales.setOpaque(true);
        ViewSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewSalesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ViewSalesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ViewSalesMouseExited(evt);
            }
        });

        BuyLot.setBackground(new java.awt.Color(0, 159, 189));
        BuyLot.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        BuyLot.setForeground(new java.awt.Color(255, 255, 255));
        BuyLot.setText("  Buy Lot");
        BuyLot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BuyLot.setOpaque(true);
        BuyLot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BuyLotMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BuyLotMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BuyLotMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(BuyLotIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BuyLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(AddLotIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(AddLot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(ViewSalesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(ViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuyLotIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuyLot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddLotIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddLot, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewSalesIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewSales, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(LogoIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(LogoIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(16, 16, 16)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(636, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuyLotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyLotMouseClicked
        BuyLotForm blf = new BuyLotForm();
        blf.setVisible(true);
    }//GEN-LAST:event_BuyLotMouseClicked

    private void AddLotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLotMouseClicked
        AddLotForm alf = new AddLotForm();
        alf.setVisible(true);
    }//GEN-LAST:event_AddLotMouseClicked

    private void ViewSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewSalesMouseClicked
       ViewSalesForm vsf = new ViewSalesForm();
       vsf.setVisible(true);
    }//GEN-LAST:event_ViewSalesMouseClicked

    private void BuyLotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyLotMouseEntered
        BuyLot.setBackground(Color.white);
        BuyLot.setForeground(new Color(0,159,189));
    }//GEN-LAST:event_BuyLotMouseEntered

    private void AddLotMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLotMouseEntered
        AddLot.setBackground(Color.white);
        AddLot.setForeground(new Color(0,159,189));
    }//GEN-LAST:event_AddLotMouseEntered

    private void ViewSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewSalesMouseEntered
        ViewSales.setBackground(Color.white);
        ViewSales.setForeground(new Color(0,159,189));
    }//GEN-LAST:event_ViewSalesMouseEntered

    private void BuyLotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BuyLotMouseExited
        BuyLot.setBackground(new Color(0,159,189));
        BuyLot.setForeground(Color.white);
    }//GEN-LAST:event_BuyLotMouseExited

    private void AddLotMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddLotMouseExited
        AddLot.setBackground(new Color(0,159,189));
        AddLot.setForeground(Color.white);
    }//GEN-LAST:event_AddLotMouseExited

    private void ViewSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewSalesMouseExited
        ViewSales.setBackground(new Color(0,159,189));
        ViewSales.setForeground(Color.white);
    }//GEN-LAST:event_ViewSalesMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstateApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RealEstateApp().setVisible(true);
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddLot;
    private javax.swing.JLabel AddLotIcon;
    private javax.swing.JLabel BuyLot;
    private javax.swing.JLabel BuyLotIcon;
    private javax.swing.JLabel LogoIcon;
    private javax.swing.JLabel ViewSales;
    private javax.swing.JLabel ViewSalesIcon;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
